[project]
name = "pruebacasobg"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chromadb>=1.0.16",
    "numpy>=2.3.2",
    "ollama>=0.5.3",
    "rapidfuzz>=3.13.0",
    "requests>=2.32.4",
]
